name: Deploy to GithHub Pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: imyelo/logseq-publish@build/fork
        with:
          src: graph
          dest: gh-pages
      - name: add a nojekyll file \
        run: touch $GITHUB_WORKSPACE/gh-pages/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: gh-pages
          clean: true
